### ISSUE TITLE
Erro na conexão online de jogo 100% (Warface) online na Sysnand com atmosphere da conf.txt

### ISSUE THREAD

**Issue by jpaulolimapm92** [CostelaCNX/CNX#11]
O jogo original Warface: Clutch, um FPS 100% online e gratuito (Muito bom), funciona normalmente quando entro no modo original. No entanto, ao entrar no modo Sysnand Atmosphere, através do arquivo conf.txt, o jogo fica preso na tela inicial, onde são exibidas opções para mudar os servidores. Parece que algo no Atmosphere está interferindo na conexão do jogo, impedindo que eu entre no modo online.

**Comment by Ital0Alve5** [comment]
> O jogo original Warface: Clutch, um FPS 100% online e gratuito (Muito bom), funciona normalmente quando entro no modo original. No entanto, ao entrar no modo Sysnand Atmosphere, através do arquivo conf.txt, o jogo fica preso na tela inicial, onde são exibidas opções para mudar os servidores. Parece que algo no Atmosphere está interferindo na conexão do jogo, impedindo que eu entre no modo online.

Não é o objetivo evitar que o usuário entre online para poupar possíveis banimentos?

**Comment by CostelaCNX** [comment]
> O jogo original Warface: Clutch, um FPS 100% online e gratuito (Muito bom), funciona normalmente quando entro no modo original. No entanto, ao entrar no modo Sysnand Atmosphere, através do arquivo conf.txt, o jogo fica preso na tela inicial, onde são exibidas opções para mudar os servidores. Parece que algo no Atmosphere está interferindo na conexão do jogo, impedindo que eu entre no modo online.

Foi uma modificação do Michael no atmosphère e não na config do pacote :(
