### ISSUE TITLE
Travamento apos a entrada no atmosfere

### ISSUE THREAD

**Issue by RodrigoM1998** [CostelaCNX/CNX#12]
Boa noite! Tudo certo?
Eu não sei se é somente comigo, porém o sistema desbloquado está dando o seguindo problema, eu instalo normalmente ele no meu sd, funciona tranquilamente os jogos, porém depois de um tempo o sistema fica muito mas muito lento, e após isso quando reinicio o console se entrar novamente no sistema desbloqueado ele vai até a parte do agradecimento e depois trava, dai tenho que reiniciar novamente mas não entra, dai somente tirando e colocando o sistema novamente, não sei se o caso é o meu console que talvez tenha que formatar o sd ou alguma coisa no cnx, porém no sistema original pelo cnx ele entra normalmente sem dar nenhum erro!

**Comment by CostelaCNX** [comment]
Nenhum problema quanto ao pacote, verifica o SD, faz uma limpeza de cachê do sd,lembre-se que a a emunand carrega do seu sd e a sysnand do módulo da nand

**Comment by lilypprnt** [comment]
To com o mesmo problema, já olhei erros, formatei e até mudei para fat32 porém o problema continua

**Comment by RodrigoM1998** [comment]
Eu troquei pro kefir para ver e ta de boas, mas nao sei o que ocorre no cnx mas sempre da esse problema

**Comment by CostelaCNX** [comment]
O que dá problema é deixar os módulos que não usam ligado.... aumentando o consumo da memória do console

**Comment by vinilimati** [comment]
Eu, no momento, só estava com o Mission Control e o Tesla habilitados. Na versão 18.1.0-4 do pack estou com os mesmos módulos mas sem travamentos. Tudo tranquilo.

**Comment by lilypprnt** [comment]
> Também estou tendo exatamento o mesmo problema. Troquei de cartão SD e continua o mesmo. Ambos os cartões são de 512gb formatados em FAT32 pelo GUI format.

Eu consegui corrigir isso, depois de inúmeros tutoriais. A única coisa que funcionou comigo foi um cartão novo zerado, fiz todo o processo de instalação e nova emunand e deu certo. Olhando o cartão antigo que eu usava ele estava corrompido (me venderam com ele em exfat)
