### ISSUE TITLE
Não esta baixando o arquivo zip

### ISSUE THREAD

**Issue by LuizSilvaDevs** [CostelaCNX/CNX#13]
Quando clico para atualizar e baixar a nova versão aparece que o arquivo baixado não é um arquivo zip, e o switch trava e eu preciso reiniciar.
Tem outra forma de instalar a nova versão sem ser diretamente pelo switch?

**Comment by CostelaCNX** [comment]
se esta falando do CNX UPDATER, é outro REPO, e é so atualizar manualmente
