### ISSUE TITLE
CNX 19.0.1-1

### ISSUE THREAD

**Issue by igor96-up** [CostelaCNX/CNX#22]
Atualizei e alguns jogos não estão abrindo.

Pede para tirar do modo avião e para vincular uma conta Nintendo. 

Jogos:

Lego Horizon e Yakuza

Com os demais jogos não tive problema , inclusive com os Nintendo Online (GBA , SNES , 64)

**Comment by CostelaCNX** [comment]
Não é problema do pacote e não dou suporte a instalação de jogos baixados.
