### ISSUE TITLE
Sem opção de Sysnand + Atmosphere

### ISSUE THREAD

**Issue by shadlustx** [CostelaCNX/CNX#23]
Gostaria de habilitar essa opção no meu menu do Hekate mas estou com dificuldades no bloco de notas .ini, poderia me auxiliar a melhor forma de como o codigo deveria ficar na pasta?

**Comment by kaduleite** [comment]
Segue abaixo o conteúdo do arquivo de configuração com as 4 opções. Use com cuidado, a chance de ter seu console banido usando as duas opções de SysNand com o desbloqueio ativado é gigante.
==========================

[config]
autoboot=0
autoboot_list=0
verification=1
backlight=100
autohosoff=2
autonogc=0
bootprotect=0
updater2p=0


[AMS (EmuMMC+Incognito)]
cal0blank=1
atmosphere=1
emummcforce=1
fss0=atmosphere/package3
kip1patch=nosigchk
icon=bootloader/res/icon_ams_emu_inc.bmp
logopath=bootloader/res/bootlogo_fusee.bmp
{ }

[AMS (SysMMC+Incognito)]
emummc_force_disable=1
cal0blank=1
atmosphere=1
kip1patch=nosigchk
fss0=atmosphere/package3
icon=bootloader/res/icon_ams_sys_inc.bmp
logopath=bootloader/res/bootlogo_sysnand.bmp
{ }

[AMS (SysMMC)]
emummc_force_disable=1
cal0blank=0
atmosphere=1
fss0=atmosphere/package3
icon=bootloader/res/icon_ams_reggie.bmp
logopath=bootloader/res/bootlogo_reggie.bmp
{ }

[Official Firmware]
emummc_force_disable=1
fss0=atmosphere/package3
stock=1
icon=bootloader/res/icon_switch_logo.bmp
{ }

**Comment by CostelaCNX** [comment]
leia os changelogs dos releases..... tem todas opções de boot.
