### ISSUE TITLE
ERROR 509

### ISSUE THREAD

**Issue by Luis-Aciole** [CostelaCNX/CNX#26]
Não estou conseguindo baixar nenhuma modificação após a atualização desse novo pacote. Tentei baixar o SNES ONLINE PACK ROMS e simplesmente não baixa e cai na tela do error 509. Já tentei atualizar o aplicativo do snes online pra versão que essas modificações requerem e mesmo assim não consegui.

**Comment by Pipow-fmf** [comment]
Aqui também está do mesmo jeito, mais cedo a do PAPERO até baixaa, mas não marcava a estrelinha na frente, era como se não tiesse feito o download, ai nao dava para desinstalar...

**Comment by CostelaCNX** [comment]
o repositorio aqui é do PACOTE CNX
