### ISSUE TITLE
Tela preta no modo rcm após injeção do payload

### ISSUE THREAD

**Issue by nobru-rj-br** [CostelaCNX/CNX#27]
Preciso de ajuda, por favor!
Estava jogando Mario Party Jamboree (Atmosphere) quando fechei o jogo o Switch congelou. Depois disso eu só consigo iniciar o console em OFW. (Funcionando normal com todos os meus cartuchos).
Quando coloco o console em modo  RCM ee ingjeto o hekate tanto por Android quanto TegraRCMGui, sem e com  micro SD a tela só fica preta.

Esses são os dois logs do tegrarcmgui diferentes que geraram em muitas tentativas:
1)
No RCM device detected
RCM Device detected
Invoking TegraRcmSmash.exe with args : "C:\Users-noBru-\Downloads\CNX.19.0.1-2\hekate_ctcaer_6.2.2 - Copia.bin"
TegraRcmSmash (32bit) 1.2.1-3 by rajkosto
Opened USB device path \?\usb#vid_0955&pid_7321#6&30afba37&0&5#{aa0dbd45-3117-f331-5c49-76bf65225042}
RCM Device with id C08000190000000804532C6401101062 initialized successfully!
Uploading payload (mezzo size: 92, user size: 109652, total size: 175868, total padded size: 176128)...
Smashing the stack!
Smashed the stack with a 0x7000 byte SETUP request!
Payload successfully injected

RCM Device detected
Invoking TegraRcmSmash.exe with args : "C:\Users-noBru-\Downloads\CNX.19.0.1-2\hekate_ctcaer_6.2.2 - Copia.bin"
TegraRcmSmash (32bit) 1.2.1-3 by rajkosto
Opened USB device path \?\usb#vid_0955&pid_7321#6&30afba37&0&5#{aa0dbd45-3117-f331-5c49-76bf65225042}
RCM Device with id C08000190000000804532C6401101062 initialized successfully!
Uploading payload (mezzo size: 92, user size: 109652, total size: 175868, total padded size: 176128)...
Win32 error 31 happened trying to write payload buffer to RCM
request!
Error while injecting payload (RC=-8)

**Comment by CostelaCNX** [comment]
O primeiro log deu certo a injeção do payload tenta trocar de SD
