### ISSUE TITLE
Atualização do CNX 19.0.1-3 removeu meus temas e mods do Smash Bros.

### ISSUE THREAD

**Issue by DanMixerBR** [CostelaCNX/CNX#29]
Olá Costela, tudo bem?

Dia **27/12** eu fiz a atualização do meu CNX pelo próprio **CNX Updater**. Verifiquei que após a atualização, alguns arquivos e pastas do meu cartão SD foram excluídos, segue abaixo a lista:
 
- Todos os meus temas do Switch que estavam na pasta "**1: SD Card\themes**"; 
- Os mods do Smash Bros, que estavam na pasta "**1: SD Card\ultimate**";
- O aplicativo **MiiPort**, que estava na pasta "**1: SD Card\switch\MiiPort**";
- Pasta de dados do MiiPort, localizada em "**1: SD Card\MiiPort\miis**".

Aparentemente a atualização **remove qualquer arquivo e pasta** que é desconhecido para o CNX Pack. Espero que isso possa ser corrigido na próxima atualização, para evitar possíveis transtornos. Também não quero fazer backup do meu cartão, sempre quando lançar uma atualização nova. Verifiquei também que o aplicativo **JKSV**, que é um gerenciador de dados salvos do Switch, está desatualizado na versão **02.23.2023**. A versão mais recente dele é a **11.05.2024** lançada em novembro de 2024.

![Screenshot_1](https://github.com/user-attachments/assets/55ff4ffc-7768-4c48-937b-31f852f13a0b)
![Screenshot_2](https://github.com/user-attachments/assets/3f939dc1-0cb1-44bd-aa60-4356add3b1a3)

**Comment by CostelaCNX** [comment]
Vlw pelo feedback, num proximo update ja atualizo o JKSV, a questão de remover as coisas ai é justamente o principio de fazer com que nada que tenha no sd que não seja do pacote seja deletada pra evitar que mesclem essas coisas fazendo com que bugs possam vir a aparecer, no seu caso ai aparentemente nada vai conflitar com o pacote em si. Vou colocar na lista de exceções de exclusão.

 Muito obrigado mais uma vez pelo feedback.

**Comment by DanMixerBR** [comment]
Muito obrigado pelo retorno, você é demais! :)

**Comment by CostelaCNX** [comment]
a pasta themes ai que vc relatou ja estava na lista de exceções, tinha alguma outra dentro dela? se sim qual nome?

**Comment by DanMixerBR** [comment]
Teve sim. Quando a gente baixa temas pelo Themezer-NX ele cria uma pasta com o título "**ThemezerNX**". Ela fica localizada em "**1: SD Card\themes**".

![image](https://github.com/user-attachments/assets/29a29fd8-0feb-4eaf-8f1c-a33894eade0a)

**Comment by DanMixerBR** [comment]
É dentro dessa pasta que os temas baixados ficam salvos.

![image](https://github.com/user-attachments/assets/223d2578-9626-4990-9980-e9432e203222)

**Comment by CostelaCNX** [comment]
feito, se puder refazer o update via updater e checar se tudo permance igual, te agradeço, a unica coisa que vai alterar ai no caso seria o JSVK

**Comment by DanMixerBR** [comment]
Certo, vou refazer o update para testar. Obrigado!

**Comment by DanMixerBR** [comment]
Acabei de refazer a atualização, a pasta de temas e o aplicativo MiiPort continuaram salvos. Mas a pasta de mods do Smash Bros. foi excluída novamente. Ela fica localizada em **1: SD Card\ultimate\mods**. Se você puder adicioná-las na lista de exceções, eu agradeço, pois possuo mais de 5 mods do Smash Bros. e é ruim ter que adicioná-los com frequência..

![image](https://github.com/user-attachments/assets/4544b146-176d-44cc-98eb-f7f340d7de38)

**Comment by DanMixerBR** [comment]
Nesta imagem, eu mostro os mods do Smash Bros que tenho. Eles utilizam o plugin **ARCropolis** que está salvo na pasta do AMS. Também tenho um backup deles no meu computador.

![image](https://github.com/user-attachments/assets/f2fda0a4-73d5-4a73-9abf-2d3058e7c14c)

**Comment by CostelaCNX** [comment]
malfeito, feito! se puder testar e dar o feedback novamente, te agradeço!

**Comment by DanMixerBR** [comment]
Olá Costela! Eu refiz a atualização do CNX novamente e **agora está tudo certo!** Os meus temas do Switch e mods do Smash Bros. foram mantidos. Agradeço de coração a sua agilidade em me responder, farei minha doação para ajudar o projeto!

**Segue abaixo as minhas sugestões para melhorar o CNX:**

- Retornar a tela de boot do pacote anterior. Essa tela do **Mario Pirata** causa uma má impressão, parece até que o desbloqueio veio do torrent chinês. Aquela tela com a frase "Muito obrigado pelo apoio de todos" é muito mais atraente e deveria ser a tela de boot definitiva;
- Substituir o "**hbmenu**" pelo "**sphaira**". Eu fiz vários testes com o sphaira, instalei jogos, atualizações e temas por ele, e não tive nenhum problema. Ele já possui uma opção nativa para substituir o hbmenu através do Álbum do Switch. O arquivo de configurações do sphaira fica localizado em "**1: SD Card\config\sphaira\config.ini**", você pode incluir este arquivo no pacote do CNX, para substituir o hbmenu pelo sphaira automaticamente;
- Segue o link para baixar o arquivo de configuração do sphaira que extraí do meu Switch. Ele já está em Português e configurado para instalar forwarders e substituir o hbmenu: https://drive.google.com/file/d/1EMrWa6ceUC3d2k6J_-3zoDLL8h_k8nns/view?usp=drive_link
- Atualizar o aplicativo JKSV, que está na versão 02.23.2023 para a versão 11.05.2024 lançada em novembro de 2024;
- Incluir o aplicativo MiiPort, ele pode ser usado para fazer o backup dos Miis;
- Remover a tradução do Smash Bros. Ultimate, localizada em "**1: SD Card\ultimate\mods\data.arc**", pois ela pode causar conflito com outros mods do Smash Bros. Mantenha somente o **ARCropolis**, que é o plugin necessário para os mods funcionarem. Ele fica localizado em "atmosphere\contents\01006A800016E000\romfs\skyline\plugins" (essa pasta já está inclusa na lista de exceções).

![Screenshot_1](https://github.com/user-attachments/assets/b7757627-504f-4ba7-9333-ce945c64c5ad)

![2024122805363200](https://github.com/user-attachments/assets/65dba515-c2eb-43f2-83b1-22ec30721bf8)

![image](https://github.com/user-attachments/assets/55f21123-c645-4439-8c89-a2e9b4192680)

**Comment by CostelaCNX** [comment]
A minha tela do Mario Jack Sparrow tão bonitinha 😣, essa não vou mexer, pelo menos não por enquanto, a tela de agradecimento foi o pelo apoio e doação da galera quando tive o problema de ter minha conta hackeada.

O sphaira no próximo update será estará sim substituindo o hbmenu, como coloquei ele no pacote neste release, deixar a galera se adaptar com ele. O JKSV vai ser atualizado no próximo release tb, a tradução do Smash eu já deixei built in no pacote pois ela precisa estar na raiz do sd, infelizmente foi a única solução que achei de deixar essa tradução aí funcionando pra galera que não tem PC.

No mais obrigado pelo feedback e sugestões, ah eu vi que se tem um projeto de tradução, me avise quando estiver pronto que eu faço questão de deixar ela disponível no CNX Updater!
