### ISSUE TITLE
Desde já agradecer o projeto, erro na 19.0.0

### ISSUE THREAD

**Issue by jpaulolimapm92** [CostelaCNX/CNX#6]
Tá acontecendo um erro ao abrir jogos originais baixados na eshop na Sysnand nessa versão 19.0.0. Em outros pacotes está funcionando, mas o seu pacote é melhor.

**Comment by CostelaCNX** [comment]
Eita! Muito obrigado pelo reconhecimento, não era pra dar nada de errado no original visto que nem sobe atmosphere lá... qual erro da pra eu investigar por favor

**Comment by jpaulolimapm92** [comment]
Não é entrando no modo original, e usando aquela opção do more configs, modo original pega de boa, mas como o meu é um modelo V1, é meu chatinho pra voltar para emunand, saindo do modo original, desde já agradeço amigo.

**Comment by CostelaCNX** [comment]
teste o novo release
