### ISSUE TITLE
Erro de atmosphere corrompendo o boot da emunand

### ISSUE THREAD

**Issue by YuryTrindade** [CostelaCNX/CNX#8]
utilizando o nx updater para baxar traduções ou apenas abrindo o updater, recebi a tela azul do atmosphere algumas vezes.
quando acontece, não consigo entrar novamente na emunand, só consigo voltar a usar reinstalando o pacote 19.0.2 novamente.

**Comment by CostelaCNX** [comment]
teste o novo release
